### ISSUE TITLE
issue about Installation

### ISSUE THREAD

**Issue by fooltux** [ktelep/EMC-Zabbix-Integration#17]
Update the Host inventory, setting it to manual to include the array serial number

hello
       this statement is in the document ,what does this mean ,I can't understan clearly . thank you very much

**Comment by ktelep** [comment]
When you create the host, there is a tab for "Host Inventory"   Clicking on this tab will bring up options to set for Automatic or Manual.  You need to set this to manual and put the serial number in for the Name.  

The current integration does not autopopulate this Host Inventory information, which is why you must manually add it.
