### ISSUE TITLE
Use "hostname" instead of serial number

### ISSUE THREAD

**Issue by chicoraf** [ktelep/EMC-Zabbix-Integration#31]
Hi. First, thanks for the hard work! I want to know if it's possible to use the hostname set in the equipment intead of the serial number in the zabbix_sender command. The ideia is to create the host in Zabbix using a friendly name, intead of the serial number. Thanks again!

**Comment by ktelep** [comment]
Theoretically it would work, but you would need to manage a mapping of the friendly name to the array serial across discovery and stats sending and make the appropriate code changes.  As of right now we use the Array Serial # because it basically acts as our 'unique key' for both the discovery processes and managing all the references between the objects associated with that serial.   We also are required to pass the array serial to the ecom server in order go gather all of the information about the system so you would somehow need to insert your friendly name in the middle.

Honestly there is very little development being done on this at this time, you're welcome to fork it and put in a pull request.

**Comment by chicoraf** [comment]
Thank you for the tips!
